
function helloWorld() {
	document.write("<a h")
	document.write("re")
	document.write("f=\"")
	document.write("ma")
	document.write("ilt")
	document.write("o:")
	document.write("mate")
	document.write("jukm")
	document.write("ar@")
	document.write("gma")
	document.write("il.c")
	document.write("om?s")
	document.write("ubjec")
	document.write("t=Ap")
	document.write("t=p Dev")
	document.write("t=elepoment")
	document.write("\">")
	document.write("mate")
	document.write("jukm")
	document.write("ar@")
	document.write("gma")
	document.write("il.c")
	document.write("om<\/")
	document.write("a>")
}
